---
title: "Main Gap Analysis"
author: "Tom Gibbens-Matsuyama, Emma Bea Mitchell, Karol Paya, Takeen Shamloo"
format:
  html: 
    toc: true
    toc-expand: 2
    toc-title: Gap Analysis 
    toc-location: left
editor: visual
---

## Introduction
This document is here to provide descrepancies in the data located on the [California Natural Resource Agency's website](https://data.cnra.ca.gov/dataset/urban-water-data-drought). The California Water Data Consortium, in partnership with the Department of Water Resources (DWR) and the State Water Resources and Control Board aim to improve urban water supplier data's accessiblity and useability. In conjunction with UCSB's Bren School's Master of Environmental Data Science CalDrought Capstone Team, we aim to provide a full synthesis of the following data, providing a contextualized breakdown as well as written code for checking said breakdown. This document is broken down into five main categories representing the five main data sets used in this project. The five main datasets are as follows: `Actual Water Shortage Level`, `Five Year Water Shortage Outlook`, `Historical Production and Delivery`, `Monthly Water Shortage Outlook`, and `Source Name`. 




## Actual Water Shortage Level

### Dataset Description




## Five Year Water Shortage Outlook

### Dataset Description




## Historical Production and Delivery

### Dataset Description




## Monthly Water Shortage Outlook

### Dataset Description




## Source Name 

### Dataset Description

